package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("Test 1", "Test 2", "Test 3"));
    submitGroupCreation();
    returnToGroupPage();
  }
}
